version: "3.8"

services:
  the-fourth-pole:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        GIT_NAME: ${GIT_NAME}
        GIT_EMAIL: ${GIT_EMAIL}
    working_dir: /usr/src
    tty: true
    ports:
      - "3000:3000"
