version: "3.8"

services:
  the-fourth-pole:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../:/usr/src
      - /usr/src/node_modules
      - /usr/src/.pnpm-store
      - /usr/src/packages/infra/node_modules
      - /usr/src/packages/server/node_modules
      - /usr/src/packages/web/user/node_modules
      - /usr/src/packages/web/admin/node_modules
    working_dir: /usr/src
    tty: true
    ports:
      - "3000:3000"
